title: Twileloop.Security
description: "An all in one library that centralizes multiple algorithms for encoding, encrypting and hashing in one place to be used anywhere in the code."
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
github:
  zip_url: https://github.com/sangeethnandakumar/Twileloop.Security/releases
  tar_url: https://www.nuget.org/packages/Twileloop.Security
